### Global Settings
legacy_layout=0
horizontal
background_alpha=0.4
font_file=/home/strahb/.local/share/fonts/JetBrainsMonoNerdFont-Regular.ttf
font_size=20
font_size_text=18
position=top
hud_no_margin
table_columns=20

### GPU Stats
gpu_name
gpu_stats
gpu_temp
gpu_mem_used
vram
gpu_color=ff8244

### CPU Stats
cpu_stats
cpu_temp
cpu_color=7FC7FF

### Power Metrics
gpu_power
cpu_power
battery_watt

### Performance Metrics
fps
frametime
frame_timing
# This makes the graph a bit more compact
histogram

### Shortcuts & Logic
toggle_hud=Ctrl_L+Shift_L+F12
toggle_hud_position=Shift_R+F11