# Font
font_family      JetBrains Mono NF
font_size        11.0

# Window & Padding
window_padding_width 10 15
# Note: "decorations None" is handled by Niri, but you can set:
hide_window_decorations yes
background_opacity 0.90
background_tint 0.4

# Cursor
cursor_shape          beam
cursor_blink_interval 0.5

# Keybindings
# Kitty handles C-S-c/v by default. 
# Word jumping (Control+Left/Right) is handled natively.
map ctrl+equal     change_font_size all +1
map ctrl+minus     change_font_size all -1
map ctrl+0         change_font_size all 0

# Scrollback
map shift+page_up   scroll_page_up
map shift+page_down scroll_page_down


# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME
