directory: ~/Music/LibraryFLAC
library: ~/.config/beets/library.db
pluginpath:
  - ~/.config/beets/beetsplug

import:
    move: yes
    write: yes
    copy: no
    resume: ask
    incremental: yes

plugins: 
    - embedart
    - convert
    - spectralcheck
    - musicbrainz
    - fetchart
    - scrub
    - replaygain
    - inline
    - info
    - mbsync
    - lastgenre
    - edit
    - lastimport
# Library naming convention
paths:
    # Use $d_folder with a conditional slash. Refer to item_fields
    default: $albumartist/$album%aunique{}/%if{$d_folder, $d_folder/}$p_track. $title
    singleton: Non-Album/$artist/$p_track. $title
    comp: Compilations/%if{$label, $label/}$album%aunique{}/%if{$d_folder, $d_folder/}$p_track. $title

fetchart:
    auto: yes             # Automatically fetch during import
    sources: coverart *   # Prioritize MusicBrainz (Cover Art Archive)
    copy_album_art: yes   # Ensure it saves the file as cover.jpg

convert:
    dest: ~/Downloads/sshfs/HiRes
    embed: no
    copy_album_art: yes
    format: keep_lossless
    formats:
        keep_lossless:
            command: ffmpeg -i $source -y -vn -c:a copy $dest
            extension: flac

lastfm:
    user: Strobii
    api_key: fb8f13d3002911cba5c6f313fcce82ee

replaygain:
    backend: ffmpeg
    auto: yes
  
fetchart:
    auto: yes
    filename: cover.jpg  # This is the "standard" name
    sources:
            - filesystem
            - coverart
            - itunes
            - amazon
            - albumart
    copy_to_dir: yes     # Ensures the image is moved to the album folder

musicbrainz:
    genres: yes      # <--- This is 'no' by default in Beets!
    extra_tags: [year, label, catalogue_number] # Optional: fetch more data
    ratelimit: 1.5

item_fields:
    # 2-digit padded track
    p_track: u"%02i" % track
    
    # 2-digit padded disc folder, but only if it's a multi-disc album
    d_folder: |
        if disctotal > 1:
            return u"%02i" % disc
        else:
            return u""
            
    # Always gets the first (highest weighted) genre from the list
    top_genre: |
        if genres:
            return genres[0]
        return u"Unknown"